services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-tq}:${POSTGRES_PASSWORD:-tq}@db:5432/${POSTGRES_DB:-tq_dev}
      PORT: '3001'
    ports:
      - '127.0.0.1:${APP_PORT:-3001}:3001'
    networks:
      - tq-net

networks:
  tq-net:
    external: true
