import { config } from '@fohte/eslint-config'
import storybook from 'eslint-plugin-storybook'

export default config(
  {
    typescript: { typeChecked: true },
    errorHandling: {},
    // Keep web/ on design tokens (see docs/design-system.md) instead of
    // Tailwind arbitrary values.
    tailwind: {
      files: ['web/**/*.ts{,x}'],
      cssConfigPath: 'web/src/index.css',
    },
  },
  {
    ignores: ['**/routeTree.gen.ts'],
  },
  ...storybook.configs['flat/recommended'],
  // vite.config.ts/vitest.config.ts are loaded through Vite's own
  // esbuild-based config loader, which doesn't resolve the package.json
  // "imports" field, unlike the Rollup pipeline that bundles the app itself.
  {
    // mockServiceWorker.js is generated by `msw init`; it must not be linted
    // or reformatted (see .prettierignore).
    ignores: ['**/mockServiceWorker.js'],
  },
  {
    // vite.config.ts/vitest.config.ts are loaded through Vite's own
    // esbuild-based config loader, which doesn't resolve the package.json
    // "imports" field, unlike the Rollup pipeline that bundles the app
    // itself. .storybook/vitest.setup.ts imports its sibling
    // .storybook/preview.ts by relative path because that file lives outside
    // src/, the only directory the "imports" field maps.
    files: [
      'web/.storybook/vitest.setup.ts',
      'web/vite.config.ts',
      'web/vitest.config.ts',
    ],
    rules: { 'no-restricted-imports': 'off' },
  },
)
