import {
  createTaskSchema,
  taskStatus,
  taskStatusReason,
  updateTaskSchema,
} from 'api/schemas/task'
import type { Command } from 'commander'
import type { InferRequestType } from 'hono/client'

import type { Client } from '#client'
import { toApiError } from '#client'
import { buildClient } from '#command-context'
import type { RecurrenceFlagOptions } from '#commands/task-recurrence'
import {
  addRecurrenceOptions,
  parseRecurrenceRule,
} from '#commands/task-recurrence'
import { printJson, printJsonWithLinkSync } from '#output'
import { fail } from '#result'
import { addSchemaOptions, pickSchemaFields } from '#schema-options'
import { splitCommaList } from '#split-comma-list'

type CreateTaskJson = InferRequestType<Client['api']['tasks']['$post']>['json']
type UpdateTaskJson = InferRequestType<
  Client['api']['tasks'][':id']['$patch']
>['json']
type UpdateStatusJson = InferRequestType<
  Client['api']['tasks'][':id']['status']['$patch']
>['json']
type UpdateParentJson = InferRequestType<
  Client['api']['tasks'][':id']['parent']['$patch']
>['json']
type CompleteTaskJson = InferRequestType<
  Client['api']['tasks'][':id']['complete']['$post']
>['json']
type FromGithubJson = InferRequestType<
  Client['api']['tasks']['from-github']['$post']
>['json']

export function registerTaskCreateCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  addSchemaOptions(
    addRecurrenceOptions(
      task
        .command('create <title>')
        .description('Create a task')
        .option('--parent-id <id>', 'Id or number of the parent task')
        .option(
          '--labels <names>',
          'Comma-separated label names to attach (unknown names are created)',
        )
        .option(
          '--blocked-by <ids>',
          'Comma-separated ids/numbers of tasks blocking this task',
        ),
    ),
    createTaskSchema,
    // labels/recurrenceRule/blockedBy (non-scalar) and parentId (union)
    // cannot be auto-generated by addSchemaOptions and are handled manually.
    ['title', 'labels', 'recurrenceRule', 'parentId', 'blockedBy'],
    { context: 'TQ_CONTEXT' },
  )
    .match(
      (command) => command,
      (error) => fail(task, error),
    )
    .action(
      async (
        title: string,
        options: Record<string, unknown> & {
          parentId?: string
          labels?: string
          blockedBy?: string
        } & RecurrenceFlagOptions,
        command: Command,
      ) => {
        const client = buildClient(command, fetchImpl).match(
          (value) => value,
          (error) => fail(command, error),
        )
        const recurrenceRule = parseRecurrenceRule(command, options)
        const json: CreateTaskJson = {
          ...pickSchemaFields(createTaskSchema, options, [
            'title',
            'labels',
            'recurrenceRule',
            'parentId',
            'blockedBy',
          ]).match(
            (value) => value,
            (error) => fail(command, error),
          ),
          title,
          ...(options.parentId !== undefined
            ? { parentId: options.parentId }
            : {}),
          ...(options.labels !== undefined
            ? { labels: splitCommaList(options.labels) }
            : {}),
          ...(options.blockedBy !== undefined
            ? { blockedBy: splitCommaList(options.blockedBy) }
            : {}),
          ...(recurrenceRule !== undefined ? { recurrenceRule } : {}),
        }
        const res = await client.api.tasks.$post({ json })
        if (!res.ok) return fail(command, await toApiError(res))
        printJsonWithLinkSync(await res.json())
      },
    )
}
export function registerTaskUpdateCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  addSchemaOptions(
    addRecurrenceOptions(
      task
        .command('update <id>')
        .description('Update a task')
        .option(
          '--blocked-by <ids>',
          'Comma-separated ids/numbers of tasks blocking this task (replaces the full set; pass an empty string to clear)',
        )
        .option(
          '--labels <names>',
          'Comma-separated label names to set (replaces the full set; unknown names are created; pass an empty string to clear)',
        ),
    ).option('--no-recurrence', "Clear the task's recurrence rule"),
    updateTaskSchema,
    // labels/recurrenceRule/blockedBy aren't scalar fields, so
    // addSchemaOptions can't turn them into flags; blockedBy, labels, and
    // recurrenceRule are hand-parsed below instead.
    ['labels', 'recurrenceRule', 'blockedBy'],
    // No TQ_CONTEXT default here (unlike list/create/search): update sends
    // only the flags the caller explicitly set, so defaulting --context would
    // silently overwrite an existing task's context on an unrelated update
    // (e.g. `task update <id> --title x`) whenever TQ_CONTEXT is set.
  )
    .match(
      (command) => command,
      (error) => fail(task, error),
    )
    .action(
      async (
        id: string,
        options: Record<string, unknown> & {
          blockedBy?: string
          labels?: string
          recurrence?: boolean
        } & RecurrenceFlagOptions,
        command: Command,
      ) => {
        const recurrenceRule = parseRecurrenceRule(command, options)
        const json: UpdateTaskJson = {
          ...pickSchemaFields(updateTaskSchema, options, [
            'labels',
            'recurrenceRule',
            'blockedBy',
          ]).match(
            (value) => value,
            (error) => fail(command, error),
          ),
          ...(options.blockedBy !== undefined
            ? { blockedBy: splitCommaList(options.blockedBy) }
            : {}),
          ...(options.labels !== undefined
            ? { labels: splitCommaList(options.labels) }
            : {}),
          ...(recurrenceRule !== undefined
            ? { recurrenceRule }
            : options.recurrence === false
              ? { recurrenceRule: null }
              : {}),
        }
        if (Object.keys(json).length === 0) {
          return fail(command, new Error('Pass at least one flag to update'))
        }

        const client = buildClient(command, fetchImpl).match(
          (value) => value,
          (error) => fail(command, error),
        )
        const res = await client.api.tasks[':id'].$patch({
          param: { id },
          json,
        })
        if (!res.ok) return fail(command, await toApiError(res))
        printJsonWithLinkSync(await res.json())
      },
    )
}

export function registerTaskDeleteCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  task
    .command('delete <id>')
    .description('Delete a task')
    .action(async (id: string, _options: unknown, command: Command) => {
      const client = buildClient(command, fetchImpl).match(
        (value) => value,
        (error) => fail(command, error),
      )
      const res = await client.api.tasks[':id'].$delete({ param: { id } })
      if (!res.ok) return fail(command, await toApiError(res))
      printJson({ deleted: true, id })
    })
}

export function registerTaskStatusCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  task
    .command('status <id> <status>')
    .description(`Update task status (${taskStatus.options.join(', ')})`)
    .action(
      async (
        id: string,
        status: string,
        _options: unknown,
        command: Command,
      ) => {
        const parsed = taskStatus.safeParse(status)
        if (!parsed.success) {
          return fail(
            command,
            new Error(parsed.error.issues[0]?.message ?? 'Invalid value'),
          )
        }

        const client = buildClient(command, fetchImpl).match(
          (value) => value,
          (error) => fail(command, error),
        )
        const json: UpdateStatusJson = { status: parsed.data }
        const res = await client.api.tasks[':id'].status.$patch({
          param: { id },
          json,
        })
        if (!res.ok) return fail(command, await toApiError(res))
        printJson(await res.json())
      },
    )
}

export function registerTaskParentCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  task
    .command('parent <id> [parentId]')
    .description("Set or clear a task's parent (omit parentId to clear it)")
    .action(
      async (
        id: string,
        parentId: string | undefined,
        _options: unknown,
        command: Command,
      ) => {
        const client = buildClient(command, fetchImpl).match(
          (value) => value,
          (error) => fail(command, error),
        )
        const json: UpdateParentJson = { parentId: parentId ?? null }
        const res = await client.api.tasks[':id'].parent.$patch({
          param: { id },
          json,
        })
        if (!res.ok) return fail(command, await toApiError(res))
        printJson(await res.json())
      },
    )
}

export function registerTaskCompleteCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  task
    .command('complete <id>')
    .description('Complete a task')
    .option(
      '--reason <reason>',
      `Why the task is being closed (${taskStatusReason.options.join(', ')}); defaults to completed`,
    )
    .option(
      '--duplicate-of <taskId>',
      'Task id this task is a duplicate of (only used when --reason duplicate)',
    )
    .action(
      async (
        id: string,
        options: { reason?: string; duplicateOf?: string },
        command: Command,
      ) => {
        let statusReason: CompleteTaskJson['statusReason']
        if (options.reason !== undefined) {
          const parsed = taskStatusReason.safeParse(options.reason)
          if (!parsed.success) {
            return fail(
              command,
              new Error(parsed.error.issues[0]?.message ?? 'Invalid value'),
            )
          }
          statusReason = parsed.data
        }

        const client = buildClient(command, fetchImpl).match(
          (value) => value,
          (error) => fail(command, error),
        )
        const json: CompleteTaskJson = {
          statusReason,
          ...(options.duplicateOf !== undefined
            ? { duplicateOfTaskId: options.duplicateOf }
            : {}),
        }
        const res = await client.api.tasks[':id'].complete.$post({
          param: { id },
          json,
        })
        if (!res.ok) return fail(command, await toApiError(res))
        printJson(await res.json())
      },
    )
}

export function registerTaskFromGithubCommand(
  task: Command,
  fetchImpl: typeof fetch,
): void {
  task
    .command('from-github <url>')
    .description('Create a task from a GitHub issue or pull request URL')
    .action(async (url: string, _options: unknown, command: Command) => {
      const client = buildClient(command, fetchImpl).match(
        (value) => value,
        (error) => fail(command, error),
      )
      const json: FromGithubJson = { url }
      const res = await client.api.tasks['from-github'].$post({ json })
      if (!res.ok) return fail(command, await toApiError(res))
      printJson(await res.json())
    })
}
