import type { Task, TaskDetail, TreeNode } from '#hooks/use-tasks'

export function makeTask(overrides: Partial<Task> = {}): Task {
  return {
    id: 'task-1',
    number: 1,
    title: 'Task title',
    description: null,
    status: 'todo',
    statusReason: null,
    duplicateOfNumber: null,
    blockedByNumbers: [],
    context: 'personal',
    commitment: 'active',
    labels: [],
    startDate: null,
    dueDate: null,
    estimatedMinutes: null,
    parentId: null,
    parentNumber: null,
    projectId: null,
    recurrenceRuleId: null,
    githubLinks: [],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    childCompletionCount: { completed: 0, total: 0 },
    ...overrides,
  }
}

export function makeTaskDetail(
  overrides: Partial<TaskDetail> = {},
): TaskDetail {
  return {
    id: '550e8400-e29b-41d4-a716-446655440000',
    number: 1,
    title: 'Implement task detail page',
    description:
      '## Why\n\nThe task detail page is needed.\n\n## What\n\n- Add inline editing\n- Add sidebar fields',
    status: 'todo',
    statusReason: null,
    duplicateOfNumber: null,
    duplicateOfTask: null,
    context: 'personal',
    commitment: 'active',
    labels: [],
    startDate: '2026-03-20',
    dueDate: '2026-03-25',
    estimatedMinutes: 90,
    parentId: null,
    projectId: null,
    recurrenceRuleId: null,
    recurrenceRule: null,
    githubLinks: [],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    titleAuthor: null,
    descriptionAuthor: null,
    childCompletionCount: { completed: 0, total: 0 },
    pages: [],
    timeBlocks: [],
    links: { outgoing: [], incoming: [] },
    blockedBy: [],
    blocking: [],
    ...overrides,
  }
}

export function makeNode(overrides: Partial<TreeNode> = {}): TreeNode {
  return {
    id: 'parent-1',
    number: 1,
    title: 'Parent Task',
    description: null,
    status: 'todo',
    statusReason: null,
    duplicateOfNumber: null,
    blockedByNumbers: [],
    context: 'personal',
    commitment: 'active',
    labels: [],
    startDate: null,
    dueDate: null,
    estimatedMinutes: null,
    parentId: null,
    parentNumber: null,
    projectId: null,
    recurrenceRuleId: null,
    githubLinks: [],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
    children: [],
    childCompletionCount: { completed: 0, total: 0 },
    ...overrides,
  }
}
