/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TasksIndexRouteImport } from './routes/tasks/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TasksTaskIdRouteImport } from './routes/tasks/$taskId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as TasksTaskIdPagesPageIdRouteImport } from './routes/tasks/$taskId_.pages.$pageId'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIndexRoute = TasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdRoute = TasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksTaskIdPagesPageIdRoute = TasksTaskIdPagesPageIdRouteImport.update({
  id: '/tasks/$taskId_/pages/$pageId',
  path: '/tasks/$taskId/pages/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$taskId/pages/$pageId': typeof TasksTaskIdPagesPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/tasks': typeof TasksIndexRoute
  '/tasks/$taskId/pages/$pageId': typeof TasksTaskIdPagesPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/inbox': typeof InboxRoute
  '/settings': typeof SettingsRoute
  '/today': typeof TodayRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/tasks/$taskId': typeof TasksTaskIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/': typeof TasksIndexRoute
  '/tasks/$taskId_/pages/$pageId': typeof TasksTaskIdPagesPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/inbox'
    | '/settings'
    | '/today'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/projects/'
    | '/tasks/'
    | '/tasks/$taskId/pages/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/inbox'
    | '/settings'
    | '/today'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/projects'
    | '/tasks'
    | '/tasks/$taskId/pages/$pageId'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/inbox'
    | '/settings'
    | '/today'
    | '/projects/$projectId'
    | '/tasks/$taskId'
    | '/projects/'
    | '/tasks/'
    | '/tasks/$taskId_/pages/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  InboxRoute: typeof InboxRoute
  SettingsRoute: typeof SettingsRoute
  TodayRoute: typeof TodayRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  TasksTaskIdRoute: typeof TasksTaskIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TasksIndexRoute: typeof TasksIndexRoute
  TasksTaskIdPagesPageIdRoute: typeof TasksTaskIdPagesPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/': {
      id: '/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof TasksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId': {
      id: '/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof TasksTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$taskId_/pages/$pageId': {
      id: '/tasks/$taskId_/pages/$pageId'
      path: '/tasks/$taskId/pages/$pageId'
      fullPath: '/tasks/$taskId/pages/$pageId'
      preLoaderRoute: typeof TasksTaskIdPagesPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  InboxRoute: InboxRoute,
  SettingsRoute: SettingsRoute,
  TodayRoute: TodayRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  TasksTaskIdRoute: TasksTaskIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TasksIndexRoute: TasksIndexRoute,
  TasksTaskIdPagesPageIdRoute: TasksTaskIdPagesPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
