[env]
DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url api dev') }}"
TEST_DATABASE_URL = "{{ exec(command=config_root ~ '/../scripts/db-url api test') }}"
_.file = ['.env', '.env.local']
